[book]
authors = ["Roxette Dillon (Lead Developer, Artist, Programmer)"]
language = "en"
multilingual = false
src = "src"
title = "HellForge Documentation"
description = "The Official Documenation for all HellForge commands, stats, items and more!"
